#!/bin/bash

	string="abbabba"
	reverse=`rev $string`
	if [ $string = $reverse ] ; then
	echo "Palindrome"
	fi


	tempstring=""
	while [ $# -gt 0 ];
	do
	tempstring="$1 $tempstring"
	shift
	done
	echo $tempstring




#	tempstring=" "
#	for (( i=0 ; i<6; i++ ))
#	do
#	tempstring="$1 $tempstring"
#	shift
#	done
#	echo $tempstring

#isInt()
#{
#	if  [ "$1" = ^[0-9]+$ ]  ||  [ "$1" = ^[0-9]+$ ] ; then
#	echo "Thats an integer"
#	else
#	echo "That was not an integer"
#	fi
#}
#
#	echo -n "Enter a number: "
#	read input
#	isInt $input


# ask a user for their favoirite colour and if it's not red
# tell them its wrong wait 3 seconds, clear the screen & ask again

#	while [ "$colour" != "red" ]
#	do
#	echo -n "What is your favourite colour? "
#	read colour
#		if [ "$colour" != "red" ]; then
#		echo "Wrong answer FOOL!!"
#		sleep 3
#		clear
#		fi
#	wait
#	done


#rename multiple abc.txt to abc.txt.old

#	for i in *.txt;
#	do
#	mv "$i" "$i.old"
#	done

#Input a value and count down to 1

#	echo -n "Input a value: "
#	read count
#	while [ $count -ne 0 ]
#	do
#	echo -n "$count "
#	count=$((count - 1))
#	done


#Menu
#	choice=1
#	while [ $choice != 0 ]
#	do
#		echo "+----------------+"
#		echo "|      MENU      |"
#		echo "| 0 Quit         |"
#		echo "| 1 Continue     |"
#		echo "+----------------+"
#		echo -n ": "
#		read choice
#	done
#	echo "Bye!"


#Output params one on each line in order
#	for i in $@
#	do
#	echo $1
#	shift
#	done



#Output params in reverse order
#echo $@ | rev
